apiVersion: apps/v1
kind: Deployment
metadata:
  name: floci
  labels:
    app: floci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: floci
  template:
    metadata:
      labels:
        app: floci
    spec:
      containers:
      - name: floci
        image: floci/floci:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4566
          name: api
        readinessProbe:
          httpGet:
            path: /_floci/health
            port: 4566
          initialDelaySeconds: 5
          periodSeconds: 10