apiVersion: apps/v1
kind: Deployment
metadata:
  name: floci
  labels:
    app: floci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: floci
  template:
    metadata:
      labels:
        app: floci
    spec:
      containers:
      - name: floci
        image: floci/floci:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: FLOCI_UI_ENABLED
          value: "false"
        ports:
        - containerPort: 4566
          name: api