apiVersion: apps/v1
kind: Deployment
metadata:
  name: floci
  labels:
    app: floci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: floci
  template:
    metadata:
      labels:
        app: floci
    spec:
      containers:
      - name: floci
        image: floci/floci:latest
        imagePullPolicy: IfNotPresent
        env:
        # Desativa a UI e serviços que forçam acesso ao Docker
        - name: FLOCI_UI_ENABLED
          value: "false"
        - name: FLOCI_SERVICES_DOCDB_MOCK
          value: "true"
        - name: FLOCI_SERVICES_EKS_MOCK
          value: "true"
        - name: FLOCI_SERVICES_MWAA_MOCK
          value: "true"
        ports:
        - containerPort: 4566
          name: api