apiVersion: v1
kind: Service
metadata:
  name: floci-service
spec:
  type: ClusterIP   # Serviço privado dentro do cluster
  selector:
    app: floci
  ports:
    - name: api
      port: 4566
      targetPort: 4566